"""boards

Revision ID: 944e9549d699
Revises: 6cb3acd5666d
Create Date: 2021-02-11 14:20:18.517091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944e9549d699'
down_revision = '6cb3acd5666d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('cheese1', sa.Integer(), nullable=False))
    op.add_column('boards', sa.Column('cheese2', sa.Integer(), nullable=False))
    op.add_column('boards', sa.Column('cheese3', sa.Integer(), nullable=False))
    op.add_column('boards', sa.Column('cracker', sa.Integer(), nullable=False))
    op.add_column('boards', sa.Column('fruit', sa.Integer(), nullable=False))
    op.add_column('boards', sa.Column('meat2', sa.Integer(), nullable=False))
    op.add_column('boards', sa.Column('meat3', sa.Integer(), nullable=False))
    op.add_column('boards', sa.Column('nut', sa.Integer(), nullable=False))
    op.add_column('boards', sa.Column('spread', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'boards', 'board_items', ['spread'], ['id'])
    op.create_foreign_key(None, 'boards', 'board_items', ['cracker'], ['id'])
    op.create_foreign_key(None, 'boards', 'board_items', ['meat3'], ['id'])
    op.create_foreign_key(None, 'boards', 'board_items', ['fruit'], ['id'])
    op.create_foreign_key(None, 'boards', 'board_items', ['cheese1'], ['id'])
    op.create_foreign_key(None, 'boards', 'board_items', ['meat2'], ['id'])
    op.create_foreign_key(None, 'boards', 'board_items', ['cheese3'], ['id'])
    op.create_foreign_key(None, 'boards', 'board_items', ['cheese2'], ['id'])
    op.create_foreign_key(None, 'boards', 'board_items', ['nut'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.drop_column('boards', 'spread')
    op.drop_column('boards', 'nut')
    op.drop_column('boards', 'meat3')
    op.drop_column('boards', 'meat2')
    op.drop_column('boards', 'fruit')
    op.drop_column('boards', 'cracker')
    op.drop_column('boards', 'cheese3')
    op.drop_column('boards', 'cheese2')
    op.drop_column('boards', 'cheese1')
    # ### end Alembic commands ###
