"""create-tables

Revision ID: f768ed251061
Revises: 
Create Date: 2021-02-11 14:59:03.705770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f768ed251061'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('boards_spread_fkey', 'boards', type_='foreignkey')
    op.drop_constraint('boards_nut_fkey', 'boards', type_='foreignkey')
    op.drop_constraint('boards_cheese3_fkey', 'boards', type_='foreignkey')
    op.drop_constraint('boards_meat2_fkey', 'boards', type_='foreignkey')
    op.drop_constraint('boards_cheese1_fkey', 'boards', type_='foreignkey')
    op.drop_constraint('boards_cracker_fkey', 'boards', type_='foreignkey')
    op.drop_constraint('boards_fruit_fkey', 'boards', type_='foreignkey')
    op.drop_constraint('boards_meat3_fkey', 'boards', type_='foreignkey')
    op.drop_constraint('boards_cheese2_fkey', 'boards', type_='foreignkey')
    op.drop_column('boards', 'cheese3')
    op.drop_column('boards', 'spread')
    op.drop_column('boards', 'cheese2')
    op.drop_column('boards', 'meat2')
    op.drop_column('boards', 'meat3')
    op.drop_column('boards', 'cracker')
    op.drop_column('boards', 'fruit')
    op.drop_column('boards', 'nut')
    op.drop_column('boards', 'cheese1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('cheese1', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('boards', sa.Column('nut', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('boards', sa.Column('fruit', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('boards', sa.Column('cracker', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('boards', sa.Column('meat3', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('boards', sa.Column('meat2', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('boards', sa.Column('cheese2', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('boards', sa.Column('spread', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('boards', sa.Column('cheese3', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('boards_cheese2_fkey', 'boards', 'board_items', ['cheese2'], ['id'])
    op.create_foreign_key('boards_meat3_fkey', 'boards', 'board_items', ['meat3'], ['id'])
    op.create_foreign_key('boards_fruit_fkey', 'boards', 'board_items', ['fruit'], ['id'])
    op.create_foreign_key('boards_cracker_fkey', 'boards', 'board_items', ['cracker'], ['id'])
    op.create_foreign_key('boards_cheese1_fkey', 'boards', 'board_items', ['cheese1'], ['id'])
    op.create_foreign_key('boards_meat2_fkey', 'boards', 'board_items', ['meat2'], ['id'])
    op.create_foreign_key('boards_cheese3_fkey', 'boards', 'board_items', ['cheese3'], ['id'])
    op.create_foreign_key('boards_nut_fkey', 'boards', 'board_items', ['nut'], ['id'])
    op.create_foreign_key('boards_spread_fkey', 'boards', 'board_items', ['spread'], ['id'])
    # ### end Alembic commands ###
