"""create-all-tables

Revision ID: 6cb3acd5666d
Revises: 
Create Date: 2021-02-11 14:17:55.550283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb3acd5666d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('item_name', sa.String(length=50), nullable=False),
    sa.Column('item_image', sa.String(), nullable=True),
    sa.Column('item_description', sa.Text(), nullable=False),
    sa.Column('boldness', sa.Float(), nullable=True),
    sa.Column('sharpness', sa.Float(), nullable=True),
    sa.Column('saltiness', sa.Float(), nullable=True),
    sa.Column('spiciness', sa.Float(), nullable=True),
    sa.Column('sweetness', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('address1', sa.String(length=255), nullable=False),
    sa.Column('address2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zipcode', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('wines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wine_type', sa.String(length=50), nullable=False),
    sa.Column('wine_name', sa.String(length=50), nullable=False),
    sa.Column('wine_image', sa.String(), nullable=True),
    sa.Column('wine_description', sa.Text(), nullable=False),
    sa.Column('wine_cost', sa.Float(), nullable=False),
    sa.Column('boldness', sa.Float(), nullable=True),
    sa.Column('sharpness', sa.Float(), nullable=True),
    sa.Column('saltiness', sa.Float(), nullable=True),
    sa.Column('spiciness', sa.Float(), nullable=True),
    sa.Column('sweetness', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_name', sa.String(length=50), nullable=False),
    sa.Column('board_description', sa.Text(), nullable=False),
    sa.Column('board_cost', sa.Float(), nullable=False),
    sa.Column('meat1', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meat1'], ['board_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('wine_id', sa.Integer(), nullable=False),
    sa.Column('shipping_address1', sa.String(length=255), nullable=False),
    sa.Column('shipping_address2', sa.String(length=255), nullable=False),
    sa.Column('shipping_city', sa.String(length=50), nullable=False),
    sa.Column('shipping_state', sa.String(length=2), nullable=False),
    sa.Column('shipping_zipcode', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['wine_id'], ['wines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_orders')
    op.drop_table('orders')
    op.drop_table('boards')
    op.drop_table('wines')
    op.drop_table('users')
    op.drop_table('board_items')
    # ### end Alembic commands ###
